version: "3"
services:
  api:
    image: imauld/api:app-0.1.0
    ports:
      - "8080:8080"
    command: "/venv/bin/gunicorn -c /api/config.py api.server:app"
    environment:
      - "ALERTS_SERVICE_HOST=alerts"
      - "ALERTS_SERVICE_PORT=8081"
  messenger:
    image: imauld/messenger:app-0.2.1
    ports:
      - "8081:8081"
    command: "/venv/bin/python app/server.py"
    environment:
      - "ALERTS_SERVICE_HOST=alerts"
      - "ALERTS_SERVICE_PORT=8081"
      - "PUSH_SERVICE_HOST=push"
      - "PUSH_SERVICE_PORT=8080"
    links:
      - msgpostgres
  msgpostgres:
    image: imauld/msgpostgres:0.1.0
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  alerts:
    image: imauld/alerts:app-0.1.3
    ports:
      - "8081:8081"
    command: "./alerts-svc"
    links:
      - localstack
    environment:
      - "AWS_ACCESS_KEY_ID=foo"
      - "AWS_SECRET_ACCESS_KEY=bar"
  localstack:
    image: atlassianlabs/localstack:0.4.3
    ports:
      - "4567-4581:4567-4581"
    environment:
      - "DATA_DIR=/tmp/localstack-alerts/data"
    volumes:
      - "localstack_data:/tmp/localstack-alerts"
volumes:
  db-data:
  localstack_data:
