---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: api
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image:  imauld/api:app-0.1.0
        imagePullPolicy: IfNotPresent
        command: 
          - "./venv/bin/gunicorn"
        args:
          - -c
          - api/config.py
          - api.server:app
        ports:
          - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: api
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: api
  type: NodePort
